"""add category to requests
Revision ID: f2dc57fe28ea
Revises: 43460e64919e
Create Date: 2026-04-12 01:15:25.700099
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2dc57fe28ea'
down_revision = '43460e64919e'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyers', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=True)
    op.create_index(op.f('ix_lawyers_user_id'), 'lawyers', ['user_id'], unique=False)
    op.drop_index('ix_payments_razorpay_order_id', table_name='payments')
    op.drop_constraint('uq_payments_request_id', 'payments', type_='unique')
    op.drop_column('payments', 'razorpay_signature')
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'razorpay_order_id')
    op.add_column('requests', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'category')
    op.add_column('payments', sa.Column('razorpay_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('razorpay_signature', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_payments_request_id', 'payments', ['request_id'])
    op.create_index('ix_payments_razorpay_order_id', 'payments', ['razorpay_order_id'], unique=False)
    op.drop_index(op.f('ix_lawyers_user_id'), table_name='lawyers')
    op.alter_column('lawyers', 'rating',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
